# Generated by Django 4.1.7 on 2023-03-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar_profile_city_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
