# Generated by Django 4.1.7 on 2023-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='ссылка на урок'),
        ),
    ]
