# Generated by Django 4.1.7 on 2023-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_author_lesson_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ссылка на материалы'),
        ),
    ]
