# Generated by Django 4.1.7 on 2023-03-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method_of_payment',
            field=models.CharField(choices=[('cash', 'наличные'), ('trans', 'перевод')], default='trans', max_length=5, verbose_name='способ оплаты'),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='успешность платежа')),
                ('error_code', models.CharField(max_length=10, verbose_name='код ошибки')),
                ('terminal_key', models.CharField(max_length=50, verbose_name='ключ терминала')),
                ('status', models.CharField(max_length=50, verbose_name='статус')),
                ('bank_payment_id', models.CharField(max_length=50, verbose_name='идентификатор платежа в системе банка')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('payment_url', models.CharField(max_length=50, verbose_name='url для оплаты')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.payment', verbose_name='платеж')),
            ],
        ),
    ]
