# Generated by Django 4.1.7 on 2023-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_payment_method_of_payment_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=500000, verbose_name='цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=100000, verbose_name='цена урока'),
        ),
    ]
