# Generated by Django 4.1.7 on 2023-03-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course_price_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='bank_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='идентификатор платежа в системе банка'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='url для оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='terminal_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ключ терминала'),
        ),
    ]
