# Generated by Django 4.1.7 on 2023-03-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_paymentlog_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='ссылка на урок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', to_field='slug', verbose_name='оплаченный урок'),
        ),
    ]
