# Generated by Django 4.1.7 on 2023-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее изменение'),
        ),
    ]
