# Generated by Django 4.1.7 on 2023-03-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_lessonupdatelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonupdatelog',
            old_name='course',
            new_name='lesson',
        ),
    ]
