# Generated by Django 4.1.7 on 2023-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_course_lessonupdatelog_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_check',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='статус платежа'),
        ),
    ]
